swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /livez:
        get:
            tags:
                - project-service
            summary: livez project-service
            description: Check if the service is alive.
            operationId: project-service#livez
            produces:
                - text/plain
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: byte
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - project-service
            summary: Download gen/http/openapi3.json
            operationId: project-service#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /projects:
        get:
            tags:
                - project-service
            summary: get-projects project-service
            description: Get all projects.
            operationId: project-service#get-projects
            parameters:
                - name: v
                  in: query
                  description: Version of the API
                  required: false
                  type: string
                  enum:
                    - "1"
                - name: page_token
                  in: query
                  description: Token to get the next page of results, if available
                  required: false
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ProjectServiceGetProjectsResponseBody'
                        required:
                            - projects
                    headers:
                        Cache-Control:
                            description: Cache control header
                            type: string
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ProjectServiceGetProjectsBadRequestResponseBody'
            schemes:
                - http
    /readyz:
        get:
            tags:
                - project-service
            summary: readyz project-service
            description: Check if the service is able to take inbound requests.
            operationId: project-service#readyz
            produces:
                - text/plain
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: byte
                "503":
                    description: Service Unavailable response.
                    schema:
                        $ref: '#/definitions/ProjectServiceReadyzNotReadyResponseBody'
            schemes:
                - http
definitions:
    Project:
        title: Project
        type: object
        properties:
            description:
                type: string
                description: A description of the project
                example: project foo is a project about bar
            id:
                type: string
                description: Project ID -- v2 id, not related to v1 id directly
                example: "123"
            managers:
                type: array
                items:
                    type: string
                    example: Qui deleniti ex architecto repellat non.
                description: A list of project managers
                example:
                    - user123
                    - user456
            name:
                type: string
                description: The pretty name of the project
                example: Foo Foundation
            slug:
                type: string
                description: Project slug, a short slugified name of the project
                example: project-slug
        description: A representation of LFX Projects.
        example:
            description: project foo is a project about bar
            id: "123"
            managers:
                - user123
                - user456
            name: Foo Foundation
            slug: project-slug
    ProjectServiceGetProjectsBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Bad request (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProjectServiceGetProjectsResponseBody:
        title: ProjectServiceGetProjectsResponseBody
        type: object
        properties:
            page_token:
                type: string
                description: Opaque token if more results are available
                example: '****'
            projects:
                type: array
                items:
                    $ref: '#/definitions/Project'
                description: Resources found
                example:
                    - description: project foo is a project about bar
                      id: "123"
                      managers:
                        - user123
                        - user456
                      name: Foo Foundation
                      slug: project-slug
                    - description: project foo is a project about bar
                      id: "123"
                      managers:
                        - user123
                        - user456
                      name: Foo Foundation
                      slug: project-slug
                    - description: project foo is a project about bar
                      id: "123"
                      managers:
                        - user123
                        - user456
                      name: Foo Foundation
                      slug: project-slug
        example:
            page_token: '****'
            projects:
                - description: project foo is a project about bar
                  id: "123"
                  managers:
                    - user123
                    - user456
                  name: Foo Foundation
                  slug: project-slug
                - description: project foo is a project about bar
                  id: "123"
                  managers:
                    - user123
                    - user456
                  name: Foo Foundation
                  slug: project-slug
                - description: project foo is a project about bar
                  id: "123"
                  managers:
                    - user123
                    - user456
                  name: Foo Foundation
                  slug: project-slug
        required:
            - projects
    ProjectServiceReadyzNotReadyResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Service is not ready yet (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
