openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for project-service
paths:
    /livez:
        get:
            tags:
                - project-service
            summary: livez project-service
            description: Check if the service is alive.
            operationId: project-service#livez
            responses:
                "200":
                    description: OK response.
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: OK
                                format: binary
                            example: OK
    /openapi.json:
        get:
            tags:
                - project-service
            summary: Download gen/http/openapi3.json
            operationId: project-service#/openapi.json
            responses:
                "200":
                    description: File downloaded
    /projects:
        get:
            tags:
                - project-service
            summary: get-projects project-service
            description: Get all projects.
            operationId: project-service#get-projects
            parameters:
                - name: v
                  in: query
                  description: Version of the API
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Version of the API
                    example: "1"
                    enum:
                        - "1"
                  example: "1"
                - name: page_token
                  in: query
                  description: Token to get the next page of results, if available
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Token to get the next page of results, if available
                    example: '****'
                  example: '****'
            responses:
                "200":
                    description: OK response.
                    headers:
                        Cache-Control:
                            description: Cache control header
                            schema:
                                type: string
                                description: Cache control header
                                example: public, max-age=300
                            example: public, max-age=300
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetProjectsResponseBody'
                            example:
                                page_token: '****'
                                projects:
                                    - description: project foo is a project about bar
                                      id: "123"
                                      managers:
                                        - user123
                                        - user456
                                      name: Foo Foundation
                                      slug: project-slug
                                    - description: project foo is a project about bar
                                      id: "123"
                                      managers:
                                        - user123
                                        - user456
                                      name: Foo Foundation
                                      slug: project-slug
                                    - description: project foo is a project about bar
                                      id: "123"
                                      managers:
                                        - user123
                                        - user456
                                      name: Foo Foundation
                                      slug: project-slug
                                    - description: project foo is a project about bar
                                      id: "123"
                                      managers:
                                        - user123
                                        - user456
                                      name: Foo Foundation
                                      slug: project-slug
                "400":
                    description: 'BadRequest: Bad request'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /readyz:
        get:
            tags:
                - project-service
            summary: readyz project-service
            description: Check if the service is able to take inbound requests.
            operationId: project-service#readyz
            responses:
                "200":
                    description: OK response.
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: OK
                                format: binary
                            example: OK
                "503":
                    description: 'NotReady: Service is not ready yet'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            description: Bad request
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        GetProjectsResponseBody:
            type: object
            properties:
                page_token:
                    type: string
                    description: Opaque token if more results are available
                    example: '****'
                projects:
                    type: array
                    items:
                        $ref: '#/components/schemas/Project'
                    description: Resources found
                    example:
                        - description: project foo is a project about bar
                          id: "123"
                          managers:
                            - user123
                            - user456
                          name: Foo Foundation
                          slug: project-slug
                        - description: project foo is a project about bar
                          id: "123"
                          managers:
                            - user123
                            - user456
                          name: Foo Foundation
                          slug: project-slug
                        - description: project foo is a project about bar
                          id: "123"
                          managers:
                            - user123
                            - user456
                          name: Foo Foundation
                          slug: project-slug
                        - description: project foo is a project about bar
                          id: "123"
                          managers:
                            - user123
                            - user456
                          name: Foo Foundation
                          slug: project-slug
            example:
                page_token: '****'
                projects:
                    - description: project foo is a project about bar
                      id: "123"
                      managers:
                        - user123
                        - user456
                      name: Foo Foundation
                      slug: project-slug
                    - description: project foo is a project about bar
                      id: "123"
                      managers:
                        - user123
                        - user456
                      name: Foo Foundation
                      slug: project-slug
                    - description: project foo is a project about bar
                      id: "123"
                      managers:
                        - user123
                        - user456
                      name: Foo Foundation
                      slug: project-slug
            required:
                - projects
        Project:
            type: object
            properties:
                description:
                    type: string
                    description: A description of the project
                    example: project foo is a project about bar
                id:
                    type: string
                    description: Project ID -- v2 id, not related to v1 id directly
                    example: "123"
                managers:
                    type: array
                    items:
                        type: string
                        example: Temporibus in cupiditate quod consequatur quo.
                    description: A list of project managers
                    example:
                        - user123
                        - user456
                name:
                    type: string
                    description: The pretty name of the project
                    example: Foo Foundation
                slug:
                    type: string
                    description: Project slug, a short slugified name of the project
                    example: project-slug
            description: A representation of LFX Projects.
            example:
                description: project foo is a project about bar
                id: "123"
                managers:
                    - user123
                    - user456
                name: Foo Foundation
                slug: project-slug
tags:
    - name: project-service
      description: The project service provides LFX Project resources.
