# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: lfx-v2-project-service
  namespace: lfx
spec:
  forwardAuth:
    address: {{ .Values.heimdall.url }}
    authResponseHeaders:
      - Authorization
