# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lfx-v2-project-service
  namespace: {{ .Values.lfx.namespace }}
  {{- with .Values.traefik.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  - name: {{ .Values.traefik.gateway.name }}
    namespace: {{ .Values.traefik.gateway.namespace }}
  hostnames:
  - "lfx-api.{{ .Values.lfx.domain }}"
  rules:
  # Main application endpoints (with authentication)
  - matches:
    - path:
        type: Exact
        value: /projects
    - path:
        type: PathPrefix
        value: /projects/
    {{- if .Values.heimdall.enabled }}
    filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: heimdall
    {{- end }}
    backendRefs:
    - name: lfx-v2-project-service
      port: {{ .Values.service.port }}
