# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lfx-v2-project-service
  namespace: lfx
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: >-
        Host(`{{.Values.ingress.hostname}}`)
      priority: 10
      # TODO: add heimdall middleware once it is working - currently it causes a 403
      # middlewares:
      #   - name: heimdall
      services:
        - kind: Service
          name: lfx-v2-project-service
          port: web
