# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: heimdall.dadrus.github.com/v1alpha4
kind: RuleSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - id: "rule:lfx:lfx-v2-member-service:openapi:get"
      allow_encoded_slashes: "off"
      match:
        methods:
          - GET
        routes:
          - path: /_memberships/openapi.json
          - path: /_memberships/openapi.yaml
          - path: /_memberships/openapi3.json
          - path: /_memberships/openapi3.yaml
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        - authorizer: allow_all
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:b2b_orgs:get"
      allow_encoded_slashes: 'off'
      match:
        methods:
          - GET
        routes:
          - path: /b2b_orgs/:uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "b2b_org:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:b2b_orgs:create"
      allow_encoded_slashes: 'off'
      match:
        methods:
          - POST
        routes:
          - path: /b2b_orgs
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: member
              object: "team:{{ .Values.app.globalOrgAdminTeamUID }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:b2b_orgs:update"
      allow_encoded_slashes: 'off'
      match:
        methods:
          - PUT
        routes:
          - path: /b2b_orgs/:uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "b2b_org:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:project_memberships:get"
      allow_encoded_slashes: 'off'
      match:
        methods:
          - GET
        routes:
          - path: /project_memberships/:uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "project_membership:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:key_contacts:get"
      allow_encoded_slashes: 'off'
      match:
        methods:
          - GET
        routes:
          - path: /key_contacts/:uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "key_contact:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:key_contacts:create"
      allow_encoded_slashes: 'off'
      match:
        methods:
          - POST
        routes:
          - path: /key_contacts
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: json_content_type
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "b2b_org:{{ "{{- .Request.Body.b2b_org_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:key_contacts:update"
      allow_encoded_slashes: 'off'
      match:
        methods:
          - PUT
        routes:
          - path: /key_contacts/:uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "key_contact:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:key_contacts:delete"
      allow_encoded_slashes: 'off'
      match:
        methods:
          - DELETE
        routes:
          - path: /key_contacts/:uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "key_contact:{{ "{{- .Request.URL.Captures.uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:admin:reindex"
      allow_encoded_slashes: 'off'
      match:
        methods:
          - POST
        routes:
          - path: /admin/reindex
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: member
              object: "team:{{ .Values.app.globalOrgAdminTeamUID }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}
