# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: heimdall.dadrus.github.com/v1alpha4
kind: RuleSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - id: "rule:lfx:lfx-v2-member-service:openapi:get"
      allow_encoded_slashes: "off"
      match:
        methods:
          - GET
        routes:
          - path: /_memberships/openapi.json
          - path: /_memberships/openapi.yaml
          - path: /_memberships/openapi3.json
          - path: /_memberships/openapi3.yaml
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        - authorizer: allow_all
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:projects:tiers:list"
      allow_encoded_slashes: "off"
      match:
        methods:
          - GET
        routes:
          - path: /projects/:project_uid/tiers
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "project:{{ "{{- .Request.URL.Captures.project_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:projects:tiers:get"
      allow_encoded_slashes: "off"
      match:
        methods:
          - GET
        routes:
          - path: /projects/:project_uid/tiers/:tier_uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "project:{{ "{{- .Request.URL.Captures.project_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:projects:memberships:list"
      allow_encoded_slashes: "off"
      match:
        methods:
          - GET
        routes:
          - path: /projects/:project_uid/memberships
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "project:{{ "{{- .Request.URL.Captures.project_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:projects:memberships:get"
      allow_encoded_slashes: "off"
      match:
        methods:
          - GET
        routes:
          - path: /projects/:project_uid/memberships/:membership_uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "project:{{ "{{- .Request.URL.Captures.project_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:projects:memberships:key-contacts:list"
      allow_encoded_slashes: "off"
      match:
        methods:
          - GET
        routes:
          - path: /projects/:project_uid/memberships/:membership_uid/key_contacts
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "project:{{ "{{- .Request.URL.Captures.project_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:projects:memberships:key-contacts:get"
      allow_encoded_slashes: "off"
      match:
        methods:
          - GET
        routes:
          - path: /projects/:project_uid/memberships/:membership_uid/key_contacts/:contact_uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "project:{{ "{{- .Request.URL.Captures.project_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:projects:memberships:key-contacts:create"
      allow_encoded_slashes: "off"
      match:
        methods:
          - POST
        routes:
          - path: /projects/:project_uid/memberships/:membership_uid/key_contacts
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "project:{{ "{{- .Request.URL.Captures.project_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:projects:memberships:key-contacts:update"
      allow_encoded_slashes: "off"
      match:
        methods:
          - PUT
        routes:
          - path: /projects/:project_uid/memberships/:membership_uid/key_contacts/:contact_uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "project:{{ "{{- .Request.URL.Captures.project_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:projects:memberships:key-contacts:delete"
      allow_encoded_slashes: "off"
      match:
        methods:
          - DELETE
        routes:
          - path: /projects/:project_uid/memberships/:membership_uid/key_contacts/:contact_uid
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: writer
              object: "project:{{ "{{- .Request.URL.Captures.project_uid -}}" }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:b2b_orgs:list"
      allow_encoded_slashes: "off"
      match:
        methods:
          - GET
        routes:
          - path: /b2b_orgs
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "project:{{ .Values.openfga.lfProjectUID }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}

    - id: "rule:lfx:lfx-v2-member-service:b2b_orgs:memberships:list"
      allow_encoded_slashes: "off"
      match:
        methods:
          - GET
        routes:
          - path: /b2b_orgs/:b2b_org_uid/memberships
      execute:
        - authenticator: oidc
        - authenticator: anonymous_authenticator
        {{- if .Values.app.use_oidc_contextualizer }}
        - contextualizer: oidc_contextualizer
        {{- end }}
        {{- if .Values.openfga.enabled }}
        - authorizer: openfga_check
          config:
            values:
              relation: auditor
              object: "project:{{ .Values.openfga.lfProjectUID }}"
        {{- else }}
        {{/*
          When OpenFGA is disabled, allow all requests.
          (Only meant for *local development* because OpenFGA should be enabled when deployed.)
        */}}
        - authorizer: allow_all
        {{- end }}
        - finalizer: create_jwt
          config:
            values:
              aud: {{ .Values.app.audience }}
