# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
name: Publish Tagged Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish:
    name: Publish Tagged Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod
          # Disable module caching since this workflow runs on tag pushes and
          # releases artifacts; caching here risks cache poisoning.
          cache: false
      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9
        with:
          version: v0.17.1
      - name: generate version without v
        id: version-no-v
        env:
          REF_NAME: ${{ github.ref_name }}
        run: echo "version=${REF_NAME//v/}" >> "$GITHUB_OUTPUT"
      - env:
          REF_NAME: ${{ github.ref_name }}
          VERSION: ${{ steps.version-no-v.outputs.version }}
        run: |
          ko build github.com/linuxfoundation/lfx-v2-project-service/cmd/project-api \
            -B \
            --platform linux/amd64,linux/arm64 \
            -t "${REF_NAME}" \
            -t "${VERSION}" \
            --sbom spdx
      - env:
          REF_NAME: ${{ github.ref_name }}
          VERSION: ${{ steps.version-no-v.outputs.version }}
        run: |
          ko build github.com/linuxfoundation/lfx-v2-project-service/scripts/root-project-setup \
            -B \
            --platform linux/amd64,linux/arm64 \
            -t "${REF_NAME}" \
            -t "${VERSION}" \
            --sbom spdx
