# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
name: Publish Container Branch

"on":
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5
        with:
          go-version-file: go.mod
      - uses: ko-build/setup-ko@d982fec422852203cfb2053a8ec6ad302280d04d  # v0.8
        with:
          version: v0.17.1
      - name: Build project-api for PR
        run: |
          ko build github.com/linuxfoundation/lfx-v2-project-service/cmd/project-api \
            -B \
            --platform linux/amd64,linux/arm64 \
            -t ${{ github.sha }} \
            -t ${{ github.head_ref }} \
            --sbom spdx
      - name: Build root-project-setup for PR
        run: |
          ko build github.com/linuxfoundation/lfx-v2-project-service/scripts/root-project-setup \
            -B \
            --platform linux/amd64,linux/arm64 \
            -t ${{ github.sha }} \
            -t ${{ github.head_ref }} \
            --sbom spdx
