name: "Project API Build"

on:
  - pull_request

permissions:
  contents: read

jobs:
  build-pr:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version: stable

      - name: Go Version
        run: go version

      - name: Configure Git to clone private Github repos
        run: git config --global url."https://${TOKEN_USER}:${TOKEN}@github.com".insteadOf "https://github.com"
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TOKEN_USER: ${{ secrets.PERSONAL_ACCESS_TOKEN_USER }}

      - name: Setup
        run: make setup-dev

      - name: Download Dependencies
        run: make deps

      - name: Build
        run: make build

      - name: Test
        run: make test
